spring:
  bot:
    plugin-list: # 配置插件列表（有序），如果插件返回0，继续执行剩余插件，如果插件返回1，终止剩余插件执行
      - cn.ling.bot.plugin.IntercepterPlugin # 拦截器
      - cn.ling.bot.plugin.AtBotPlugin # 艾特插件
      - cn.ling.bot.plugin.LogPlugin # 日志插件
      - cn.ling.bot.plugin.MyPlugin # 我的插件
server:
  port: 8081